### ISSUE TITLE
 improve repo-linter to look for 2 types of OSS readme header images to support dark mode

### ISSUE THREAD

**Issue by jpvajda** [newrelic/.github#29]
DevEn wanted to make a request to improve repo-linter to look for 2 types of OSS readme header images as the one's it checks for is a version that isn't dark mode friendly.  We've been using a better version in our repos lately, but noticed repo linter flags it. 

[ Here is where the  ruleset files are](https://github.com/newrelic/.github/tree/main/repolinter-rulesets) and[ here is an example of where ](https://github.com/newrelic/.github/blob/644777d38ba6089bf27aa95d517204bd323207db/repolinter-rulesets/community-project.yml#L63)we'd like to see an OR  statement looking for both images.

You can see how we are using a darkmode friendly header image in this repo. https://github.com/newrelic/instant-observability-website

```
[![Community Project header](https://opensource.newrelic.com/static/Community_Project-7c4805883d6396086f907f1c716477cd.png)](https://opensource.newrelic.com/oss-category/#community-project)
```

We suggest supporting both types as if you change the rule set to darkmode only it would flag a lot of repos which may not have active maintainers to fix them.

**Comment by jbeveland27** [comment]
Closed by https://github.com/newrelic/.github/pull/34
